Add Windows support for raw_display
urwid/urwid pull request #448
Opened 2021-01-04 14:16 UTC by mhils

##### Checklist
- [x] I've ensured that similar functionality has not already been implemented
- [x] I've ensured that similar functionality has not earlier been proposed and declined
- [x] I've branched off the `master` or `python-dual-support` branch
- [x] I've merged fresh upstream into my branch recently
- [x] I've ran `tox` successfully in local environment *(yes, but I do not have 2.7, 3.5, and pypy at hand)*
- [x] I've included docstrings and/or documentation and/or examples for my code (if this is a new feature)

##### Description:

Inspired by @asmith-kepler's fantastic work in #447, I set out to implement Windows support for raw_display. Turns out that this is all working pretty seamlessly with the latest Windows console improvements. 🎉 

Main changes:

 - Use `socket.socketpair()` instead of `os.pipe()` on all OSes as Windows doesn't support non-socket file descriptors in `select()`. This probably has a tiny amount of overhead, but works across all platforms. 
 - Use ctypes to interface with the Windows API, which works without any additional dependencies.
 - Use a dedicated thread to read input from the Windows console and pipe it into another socketpair, which is then processed by raw_display. This is slightly ugly, but works across all events loops.

2023-03-31 07:42 UTC, penguinolog commented on urwid/raw_display.py
> +            hOut = win32.GetStdHandle(win32.STD_OUTPUT_HANDLE)
will be hood if such long branches will be in own methods like:
```python
if IS_WINDOWS:
    self.windows_signal_init()
else:
    self.signal_init()
```

2023-03-31 07:43 UTC, penguinolog commented on urwid/raw_display.py
> +            self._input_thread = None
no `wait` / `join`?

2023-03-31 07:45 UTC, penguinolog commented on urwid/raw_display.py
> +                if IS_WINDOWS:
better to make dedicated methods for both branches

2023-03-31 07:48 UTC, penguinolog requested changes
please split logic to reduce platform specific `if`/`else` branches size

2023-12-08 11:31 UTC, closed without merging

2023-12-08 11:31 UTC, penguinolog commented
Restored updated, tested and merged

2023-12-08 18:24 UTC, mhils commented
I totally missed the comments  in March, my apologies. Thanks for taking care of things, this is super duper fantastic! :smiley: :cake: :rocket: